/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projecty4;

import java.awt.Color;

/**
 *
 * @author mariavengerska
 */
public class dashboard extends javax.swing.JFrame {
private int userid;
    /**
     * Creates new form dashboard
     */
    public dashboard(int userid) {
        initComponents();
        this.userid=userid;
        loadtransaction();
        setbalance();
        hello();
        updatetotals();
        updatecolour();
    }
private void loadtransaction() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) table.getModel();

    model.setRowCount(0);

    for (String[] row : database.gettransactions(userid)) {
        model.addRow(row);
    }
}
private void hello(){
    String username = database.getusername(userid);
    hellol.setText("Hello "+username+"!");
}
private void setbalance(){
    double balance = database.getbalance(userid);
    balancel.setText("Balance: " + balance + " Kč");
}

private void updatetotals() {
    double income = database.getincome(userid);
    double expense = database.getexpense(userid);

    incomel.setText("Total income: " + income + " Kč");
    expensel.setText("Total expense: " + expense + " Kč");
}
private void updatecolour() {
    double balance = database.getbalance(userid);

    if (balance < 0) {
        balancel.setForeground(Color.RED);   
    } else {
        balancel.setForeground(Color.BLACK); 
    }}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        balancel = new javax.swing.JLabel();
        hellol = new javax.swing.JLabel();
        amountf = new javax.swing.JTextField();
        categoryb = new javax.swing.JComboBox<>();
        typeb = new javax.swing.JComboBox<>();
        addb = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        utilityb = new javax.swing.JButton();
        incomel = new javax.swing.JLabel();
        expensel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setToolTipText("");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type", "Category", "Amount"
            }
        ));
        jScrollPane1.setViewportView(table);

        balancel.setFont(new java.awt.Font("PT Serif", 1, 14)); // NOI18N
        balancel.setText("Balance: 00.00 Kč");
        balancel.setToolTipText("");

        hellol.setFont(new java.awt.Font("PT Serif", 1, 14)); // NOI18N
        hellol.setText("Hello ...!");
        hellol.setToolTipText("");

        amountf.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        amountf.setText("00.0");
        amountf.setToolTipText("");
        amountf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountfActionPerformed(evt);
            }
        });

        categoryb.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        categoryb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pocket money", "Incentive", "Food", "Clothes", "Spotify", "other" }));
        categoryb.setToolTipText("");

        typeb.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        typeb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Income", "Expense" }));
        typeb.setToolTipText("");

        addb.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        addb.setText("Add");
        addb.setToolTipText("");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        jToggleButton1.setText("Salary");
        jToggleButton1.setToolTipText("");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        utilityb.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        utilityb.setText("Utility Bills");
        utilityb.setToolTipText("");
        utilityb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitybActionPerformed(evt);
            }
        });

        incomel.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        incomel.setText("Total income:...");
        incomel.setToolTipText("");

        expensel.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        expensel.setText("Total expense: ...");
        expensel.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        jLabel1.setText("Type");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        jLabel3.setText("Category");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        jLabel4.setText("Amount");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        jLabel5.setText("Shortcuts:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("PT Serif", 1, 14)); // NOI18N
        jLabel6.setText("Log activity");
        jLabel6.setToolTipText("");

        jButton1.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        jButton1.setText("Leave");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(hellol, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(balancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jToggleButton1)
                                .addGap(39, 39, 39)
                                .addComponent(utilityb)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(amountf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(typeb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(47, 47, 47)
                                                        .addComponent(jLabel1))
                                                    .addComponent(categoryb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(35, 35, 35)
                                                        .addComponent(jLabel3))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(incomel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expensel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hellol)
                    .addComponent(balancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton1)
                            .addComponent(utilityb)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amountf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addb)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expensel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountfActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        Double amount = Double.parseDouble(amountf.getText());
        String type = typeb.getSelectedItem().toString();
        String category = categoryb.getSelectedItem().toString();
        database.addtransaction(userid, amount, type, category);
        loadtransaction();
        setbalance();
         updatetotals();
         updatecolour();
        amountf.setText("00.0");
    }//GEN-LAST:event_addbActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        double salary = database.getsalary(userid);

    database.addtransaction(userid, salary, "Income", "salary");

    loadtransaction();
    setbalance();
     updatetotals(); 
     updatecolour();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void utilitybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitybActionPerformed
        double utilitybills = database.getutilitybills(userid);

    database.addtransaction(userid, utilitybills, "Expense", "Utility bills");

    loadtransaction();
    setbalance();
     updatetotals(); updatecolour();
    }//GEN-LAST:event_utilitybActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addb;
    private javax.swing.JTextField amountf;
    private javax.swing.JLabel balancel;
    private javax.swing.JComboBox<String> categoryb;
    private javax.swing.JLabel expensel;
    private javax.swing.JLabel hellol;
    private javax.swing.JLabel incomel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> typeb;
    private javax.swing.JButton utilityb;
    // End of variables declaration//GEN-END:variables
}
